#!/usr/bin/env bash
# Capture the Tier-2 access-domain event streams that the live collectors read.
#
# Neither stream is generated by CA-ZTCF. The 5G stream is what Open5GS itself
# logs about registrations and PDU sessions; the WLAN stream is what hostapd logs
# about association, the RSN handshake and EAP-TLS. The collectors in
# src/ca_ztcf/collectors/nr_open5gs.py and wlan_hwsim.py parse these lines
# directly, so an experiment reading them is reading the access networks rather
# than anything the harness invented.
#
# SOFTWARE-BASED TESTBED. No physical radio.
set -euo pipefail

OUT="${OUT_DIR:-/var/lib/ca-ztcf/tier2}"
NR_STREAM="${OUT}/open5gs-events.log"
WLAN_STREAM="${OUT}/hostapd.log"

log() { echo "[tier2-capture] $*"; }

start() {
  sudo install -d -m 0775 "${OUT}"
  stop
  # -n 2000 replays recent history before following, so sessions that were
  # already established when the capture started are visible. These are the core's
  # own log lines either way.
  : > /tmp/ca-ztcf-nr-capture.marker
  sudo setsid bash -c "exec journalctl -f -n 2000 -o cat \
    -u open5gs-smfd -u open5gs-upfd -u open5gs-amfd >> ${NR_STREAM} 2>/dev/null" \
    < /dev/null > /dev/null 2>&1 &
  disown 2>/dev/null || true
  sleep 1
  log "5G stream  -> ${NR_STREAM}"
  log "WLAN stream -> ${WLAN_STREAM} (written by hostapd)"
}

stop() {
  sudo rm -f "${NR_STREAM}" 2>/dev/null || true
  # Bracketed so the pattern cannot match this script's own command line.
  sudo pkill -f "[j]ournalctl -f -n 2000 -o cat -u open5gs" 2>/dev/null || true
}

status() {
  printf "  5G capture   %s (%s lines)\n" \
    "$(pgrep -f '[j]ournalctl -f -n 2000 -o cat -u open5gs' >/dev/null && echo running || echo stopped)" \
    "$(wc -l < "${NR_STREAM}" 2>/dev/null || echo 0)"
  printf "  WLAN capture %s (%s lines)\n" \
    "$(pgrep -x hostapd >/dev/null && echo running || echo stopped)" \
    "$(sudo wc -l < "${WLAN_STREAM}" 2>/dev/null || echo 0)"
}

case "${1:-}" in
  start)  start ;;
  stop)   stop ;;
  status) status ;;
  *) echo "usage: $0 {start|stop|status}" >&2; exit 2 ;;
esac
